# Generated by Django 2.2.1 on 2019-09-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('venue', models.CharField(max_length=128)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('secret_code', models.CharField(max_length=10)),
            ],
        ),
    ]
